Attribute:
  enabled: false

DuplicateMethodCall:
  max_calls: 3

FeatureEnvy:
  enabled: false

IrresponsibleModule:
  enabled: false

PrimaDonnaMethod:
  enabled: false

TooManyStatements:
  enabled: true
  exclude:
  - initialize
  - perform
  - change
  - up
  - down
  max_statements: 5

"app/workers":
  UtilityFunction:
    enabled: false

"db/migrate":
  DuplicateMethodCall:
    enabled: false
  NestedIterators:
    enabled: false
  UncommunicativeVariableName:
    enabled: false
  UtilityFunction:
    enabled: false