# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.0.1'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'aasm'
gem 'activerecord'
gem 'dotenv'
gem 'rake'
gem 'sqlite3'
gem 'telegram-bot-ruby'
gem 'whenever', require: false

group :test do
  gem 'database_cleaner-active_record'
  gem 'factory_bot'
  gem 'faker'
  gem 'shoulda-matchers', '~> 4.0'
end
