# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'activerecord'
gem 'dotenv'
gem 'pg'
gem 'telegram-bot-ruby'

group :development do
  gem 'pry'
end
