# frozen_string_literal: true

require 'standalone_migrations'
require 'dotenv'
require_relative 'lib/teacher'
require_relative 'lib/actions'

StandaloneMigrations::Tasks.load_tasks

namespace :bot do
  desc 'Send words'
  task :send do
    Teacher.send_word
  end

  desc 'Send Reminder'
  task :remind do
    Teacher.remind
  end
end
