# frozen_string_literal: true

# rubocop:disable Rails/RakeEnvironment

require 'standalone_migrations'
require 'dotenv'
require_relative 'lib/teacher'

StandaloneMigrations::Tasks.load_tasks

namespace :bot do
  desc 'Send words'
  task :send do
    Teacher.send_word
  end

  desc 'Send Reminder'
  task :remind do
    Teacher.remind
  end
end

# rubocop:enable Rails/RakeEnvironment
