class Migrate::Schema
  def foo
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
    puts 'big method'
  end
  
  def method_with_block
    2.times do
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
      puts 'big block'
    end
  end
end
