2.times do
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
  puts 'Block more than 25 lines'
end