# frozen_string_literal: true

require_relative 'config/environment'
require 'sinatra/activerecord/rake'
require_relative 'lib/notify_handler'

namespace :payload do
  desc 'Send out lesson messages'
  task :send_messages do
    NotifyHandler.perform
  end
end
