# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'telegram-bot-ruby', '~> 0.15.0'

gem 'dotenv', '~> 2.7'

gem 'rspec', '~> 3.10'

gem 'activerecord', '~> 6.0'

gem 'standalone_migrations', '~> 6.0'

gem 'rake', '~> 13.0'

gem 'pg', '~> 1.2'

gem 'pry', '~> 0.14.1'

gem 'shoulda-matchers', require: false

gem 'factory_bot'

gem 'database_cleaner-active_record'

gem 'whenever', require: false
