# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'rspec', '~> 3.10'

gem 'slop', '~> 4.8'

gem 'faraday', '~> 1.3'

gem 'faraday_middleware', '~> 1.0'
