# frozen_string_literal: true

source 'https://rubygems.org'

# Specify your gem's dependencies in checker.gemspec
gemspec

gem 'httparty'
gem 'rake', '~> 12.0'

group :test do
  gem 'rspec'
  gem 'webmock'
end
