# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

gem 'rake', '~> 13.0'

group :test do
  gem 'rspec', '~> 3.0'
end

group :development, :test do
  gem 'rubocop', '~> 1.12.1', require: false
  gem 'rubocop-rake', '~> 0.5.1', require: false
  gem 'rubocop-rspec', '~> 2.2.0', require: false
end
