# frozen_string_literal: true

source 'https://rubygems.org'

gem 'telegramAPI'
gem 'sinatra'

gem 'sinatra-activerecord'
gem 'activerecord'
gem 'pg'

gem 'dotenv-rails'
gem 'json'
gem 'progress_bar'

gem 'whenever', require: false
gem 'rake'
